export const GET_PRICING_PLAN = "GET_PRICING_PLAN";
export const ADD_PRICING_PLAN = "ADD_PRICING_PLAN";
export const EDIT_PRICING_PLAN = "EDIT_PRICING_PLAN";
export const DELETE_PRICING_PLAN = "DELETE_PRICING_PLAN";

export const GET_TESTMONIAL = "GET_TESTMONIAL";
export const ADD_TESTMONIAL = "ADD_TESTMONIAL";
export const EDIT_TESTMONIAL = "EDIT_TESTMONIAL";
export const DELETE_TESTMONIAL = "DELETE_TESTMONIAL";

export const GET_BUSINESS_CATEGORY = "GET_BUSINESS_CATEGORY";
export const ADD_BUSINESS_CATEGORY = "ADD_BUSINESS_CATEGORY";
export const EDIT_BUSINESS_CATEGORY = "EDIT_BUSINESS_CATEGORY";
export const DELETE_BUSINESS_CATEGORY = "DELETE_BUSINESS_CATEGORY";

export const GET_ANNOUCEMENT = "GET_ANNOUCEMENT";
export const ADD_ANNOUCEMENT = "ADD_ANNOUCEMENT";
export const EDIT_ANNOUCEMENT = "EDIT_ANNOUCEMENT";
export const DELETE_ANNOUCEMENT = "DELETE_ANNOUCEMENT";
export const GET_BANNER = "GET_BANNER";
export const ADD_BANNER = "ADD_BANNER";
export const EDIT_BANNER = "EDIT_BANNER";
export const DELETE_BANNER = "DELETE_BANNER";
